package com.caltyfarm.caltyfarm.utils

const val PHONE_NUMBER_CODE = "PHONE_NUMBER_CODE"

const val ARTICLE_ID_CODE = "ARTICLE_ID_CODE"

const val REQUEST_PHONE_CODE = 102

const val REQUEST_FINE_LOCATION = 103

const val SHOP_CODE = "SHOP_CODE"

const val ORDER_CODE = "ORDER_CODE"

const val SELECTED_ITEM_CODE = "SELECTED_ITEMS"

const val PERMISSIONS_REQUEST_ACCESS_FINE_LOCATION = 104

const val DEFAULT_ZOOM = 13f